### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by antranapp** [SwiftFiddle/swiftfiddle-formatter#8]
There seems to be a SSL issue

<img width="734" alt="Screenshot 2021-08-12 at 11 38 22 AM" src="https://user-images.githubusercontent.com/478757/129134850-b1df8ad6-9725-469a-af52-117eb6e02cc4.png">

**Comment by kishikawakatsumi** [comment]
@antranapp I can't reproduce it in my environment, can you tell me more about how it happens?

**Comment by kishikawakatsumi** [comment]
Close this issue for now because I cannot reproduce it. Feel free to reopen if you still have the same error or you have further information.

**Comment by antranapp** [comment]
Sorry for being late. I think my corporate firewall caused the problem. Opening it in home network seems to be fine.

**Comment by kishikawakatsumi** [comment]
Thank you for your reply. Happy to here that 😄
